name: API Status Script

on:
  workflow_dispatch:
jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install git+https://github.com/Vivekkumar-IN/TheApi

      - name: Run API Status Script
        run: |
          python script.py

      - name: Configure Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git stash
          git pull origin main
          git stash pop
          git add README.md
          git commit -m "Update Status of TheApi"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
